FROM openjdk:21-jdk-slim AS build
WORKDIR /app
COPY . /app
RUN ./gradlew dependencies --no-daemon
RUN chmod +x gradlew
RUN ./gradlew build --no-daemon
COPY build/libs/*.jar /app/app.jar
CMD ["java", "-jar", "app.jar"]
EXPOSE 8000
