spring:
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa

  jwt:
    secret: ThisIsTestDontUseThisOnProductService
    access-token-expired-ms: 600000 # 10 minutes
    refresh-token-expired-ms: 86400000 # 1 day
  jpa:
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 200
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect

  security:
    oauth2:
      client:
        registration:
          google:
            client-name: google
            client-id: 694693785172-m0i9kmlib8vuup30g6jnls8m50i55voq.apps.googleusercontent.com
            client-secret: ${{ secrets.GOOGLE_CLIENT_SECRET }}
            redirect-uri: http://localhost:8000/login/oauth2/code/google
            authorization-grant-type: authorization_code
            scope:
              - profile
              - email

springdoc:
  swagger-ui:
    groups-order: DESC
    tags-sorter: alpha
    path: /api-test
    enabled: true
  paths-to-match:
    - /v1/**
  api-docs:
    enabled: true
server:
  port: 8000
  address: 0.0.0.0

crawler:
  base-url: localhost:3000/blog/
  tistory-uri: tistory/
  velog-uri: velog/