name: Deploy Containers

on:
  push:
    branches: [ "main" ]

jobs:
  upload-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      # Gradle 권한 변경
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      # Gradle 캐싱
      - name: Gradle Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build JAR
        run: ./gradlew clean build --no-daemon

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile_Spring
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/toasting-spring:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/toasting-spring:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/toasting-spring:buildcache,mode=max

  build-and-deploy:
    needs: upload-images
    runs-on: ubuntu-latest
    steps:
      - name: Create .env file
        run: |
          echo "DOCKER_HUB_USERNAME=${{ secrets.DOCKER_HUB_USERNAME }}" >> .env
          echo "SPRING_DATASOURCE_URL=${{ secrets.SPRING_DATASOURCE_URL }}" >> .env
          echo "SPRING_DATASOURCE_USERNAME=${{ secrets.SPRING_DATASOURCE_USERNAME }}" >> .env
          echo "SPRING_DATASOURCE_PASSWORD=${{ secrets.SPRING_DATASOURCE_PASSWORD }}" >> .env
          echo "SPRING_DATASOURCE_HIKARI_SCHEMA=${{ secrets.SPRING_DATASOURCE_HIKARI_SCHEMA}}" >> .env
          echo "SPRING_JWT_SECRET=${{ secrets.SPRING_JWT_SECRET }}" >> .env
          echo "SPRING_PROFILES_ACTIVE=prod" >> .env

      - name: Copy docker-compose and .env via SCP
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.PROD_EC2_HOST }}
          username: ${{ secrets.PROD_EC2_USERNAME }}
          key: ${{ secrets.PROD_EC2_KEY }}
          port: ${{ secrets.PROD_EC2_PORT }}
          source: "./docker-compose.yml,.env"
          target: "/home/toasting/"

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.PROD_EC2_HOST }}
          username: ${{ secrets.PROD_EC2_USERNAME }}
          key: ${{ secrets.PROD_EC2_KEY }}
          port: ${{ secrets.PROD_EC2_PORT }}
          script: |
            cd /home/toasting
      
            sudo docker compose down
            sudo docker compose pull
            sudo docker image prune -a -f
            sudo docker compose up --build -d
            rm -f .env
